version: '2'

services:
  php-dev-mysql:
    container_name: "php-dev-mysql"
    image: mysql:5.6.35
    volumes:
      - ./mysql:/var/lib/mysql
    # 文字コード設定(デフォルトがlatin1なので)
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"

    # user password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: php-dev

  php-dev-ap:
    build: ./php-dev
    container_name: "php-dev-ap"
    image: php-dev:latest
    ports:
      - "80:80"
    links:
      - "php-dev-mysql"

    # 端末を起動したままにする
    tty: true
    volumes:
      - ./works:/root/works
